export const TOGGLE_PAYMENT_FORM = 'paymentPage.TOGGLE_PAYMENT_FORM';
export const SAVE_PAYMENT_AMOUNT = 'paymentPage.SAVE_PAYMENT_AMOUNT';
export const SUBMIT_PAYMENT = 'paymentPage.SUBMIT_PAYMENT';
export const UPDATE_CREDIT_CARD_DETAIL =
  'paymentPage.UPDATE_CREDIT_CARD_DETAIL';
export const UPDATE_PAYMENT_AMONNT = 'paymentPage.UPDATE_PAYMENT_AMONNT';
export const BANK_PAYMENT_GATEWAY_ERROR =
  'paymentPage.BANK_PAYMENT_GATEWAY_ERROR';
export const PAYMENT_SUCCESS = 'paymentPage.PAYMENT_SUCCESS';
export const UPDATE_FORM_VALIDATION_STATE = 'paymentPage.UPDATE_FORM_VALIDATION_STATE';
